paises = {
    'Afeganistão':'Cabul',
    'África do Sul':'Pretória',
    'Albânia':'Tirana',
    'Alemanha':'Berlim',
    'Andorra':'Andorra-a-Velha',
    'Angola':'Luanda',
    'Antiga e Barbuda':'São João',
    'Arábia Saudita':'Riade',
    'Argélia':'Argel',
    'Argentina':'Buenos Aires',
    'Arménia':'Erevã',
    'Austrália':'Camberra',
    'Áustria':'Viena',
    'Azerbaijão':'Bacu',
    'Bahamas':'Nassau',
    'Bangladexe':'Daca',
    'Barbados':'Bridgetown',
    'Barém':'Manama',
    'Bélgica':'Bruxelas',
    'Belize':'Belmopã',
    'Benim':'Porto Novo',
    'Bielorrússia':'Minsque',
    'Bolívia':'Sucre',
    'Bósnia e Herzegovina':'Saraievo',
    'Botsuana':'Gaborone',
    'Brasil':'Brasília',
    'Brunei':'Bandar Seri Begauã',
    'Bulgária':'Sófia',
    'Burquina Faso':'Uagadugu',
    'Burúndi':'Bujumbura',
    'Butão':'Timbu',
    'Cabo Verde':'Praia',
    'Camarões':'Iaundé',
    'Camboja':'Pnom Pene',
    'Canadá':'Otava',
    'Catar':'Doa',
    'Cazaquistão':'Astana',
    'Chade':'Jamena',
    'Chile':'Santiago',
    'China':'Pequim',
    'Chipre':'Nicósia',
    'Colômbia':'Bogotá',
    'Comores':'Moroni',
    'Congo-Brazzaville':'Brazavile',
    'Coreia do Norte':'Pionguiangue',
    'Coreia do Sul':'Seul',
    'Cosovo':'Pristina',
    'Costa do Marfim':'Iamussucro',
    'Costa Rica':'São José',
    'Croácia':'Zagrebe',
    'Cuaite':'Cidade do Cuaite',
    'Cuba':'Havana',
    'Dinamarca':'Copenhaga',
    'Dominica':'Roseau',
    'Egito':'Cairo',
    'Emirados Árabes Unidos':'Abu Dabi',
    'Equador':'Quito',
    'Eritreia':'Asmara',
    'Eslováquia':'Bratislava',
    'Eslovénia':'Liubliana',
    'Espanha':'Madrid',
    'Essuatíni':'Lobamba',
    'Estado da Palestina':'Jerusalém Oriental',
    'Estados Unidos':'Washington, D.C.',
    'Estónia':'Talim',
    'Etiópia':'Adis Abeba',
    'Fiji':'Suva',
    'Filipinas':'Manila',
    'Finlândia':'Helsínquia',
    'França':'Paris',
    'Gabão':'Libreville',
    'Gâmbia':'Banjul',
    'Gana':'Acra',
    'Geórgia':'Tebilíssi',
    'Granada':'São Jorge',
    'Grécia':'Atenas',
    'Guatemala':'Cidade da Guatemala',
    'Guiana':'Georgetown',
    'Guiné':'Conacri',
    'Guiné Equatorial':'Malabo',
    'Guiné-Bissau':'Bissau',
    'Haiti':'Porto Príncipe',
    'Honduras':'Tegucigalpa',
    'Hungria':'Budapeste',
    'Iémen':'Saná',
    'Ilhas Marechal':'Majuro',
    'Índia':'Nova Déli',
    'Indonésia':'Jacarta',
    'Irão':'Teerão',
    'Iraque':'Bagdade',
    'Irlanda':'Dublim',
    'Islândia':'Reiquiavique',
    'Israel':'Jerusalém',
    'Itália':'Roma',
    'Jamaica':'Kingston',
    'Japão':'Tóquio',
    'Jibuti':'Jibuti',
    'Jordânia':'Amã',
    'Laus':'Vienciana',
    'Lesoto':'Maseru',
    'Letónia':'Riga',
    'Líbano':'Beirute',
    'Libéria':'Monróvia',
    'Líbia':'Trípoli',
    'Listenstaine':'Vaduz',
    'Lituânia':'Vílnius',
    'Luxemburgo':'Luxemburgo',
    'Macedónia do Norte':'Escópia',
    'Madagáscar':'Antananarivo',
    'Malásia':'Cuala Lumpur',
    'Maláui':'Lilôngue',
    'Maldivas':'Malé',
    'Mali':'Bamaco',
    'Malta':'Valeta',
    'Marrocos':'Rebate',
    'Maurícia':'Porto Luís',
    'Mauritânia':'Nuaquechote',
    'México':'Cidade do México',
    'Mianmar':'Nepiedó',
    'Micronésia':'Paliquir',
    'Moçambique':'Maputo',
    'Moldávia':'Quixinau',
    'Mónaco':'Mónaco',
    'Mongólia':'Ulã Bator',
    'Montenegro':'Podgoritsa',
    'Namíbia':'Vinduque',
    'Nauru':'Iarém',
    'Nepal':'Catmandu',
    'Nicarágua':'Manágua',
    'Níger':'Niamei',
    'Nigéria':'Abuja',
    'Noruega':'Oslo',
    'Nova Zelândia':'Wellington',
    'Omã':'Mascate',
    'Países Baixos':'Amesterdão',
    'Palau':'Ngerulmud',
    'Panamá':'Cidade do Panamá',
    'Papua Nova Guiné':'Porto Moresby',
    'Paquistão':'Islamabade',
    'Paraguai':'Assunção',
    'Peru':'Lima',
    'Polónia':'Varsóvia',
    'Portugal':'Lisboa',
    'Quénia':'Nairóbi',
    'Quirguistão':'Bisqueque',
    'Quiribáti':'Taraua do Sul',
    'Reino Unido':'Londres',
    'República Centro-Africana':'Bangui',
    'República Checa':'Praga',
    'República Democrática do Congo':'Quinxassa',
    'República Dominicana':'São Domingos',
    'Roménia':'Bucareste',
    'Ruanda':'Quigali',
    'Rússia':'Moscovo',
    'Salomão':'Honiara',
    'Salvador':'São Salvador',
    'Samoa':'Apia',
    'Santa Lúcia':'Castries',
    'São Cristóvão e Neves':'Basseterre',
    'São Marinho':'São Marinho',
    'São Tomé e Príncipe':'São Tomé',
    'São Vicente e Granadinas':'Kingstown',
    'Seicheles':'Vitória',
    'Senegal':'Dacar',
    'Serra Leoa':'Freetown',
    'Sérvia':'Belgrado',
    'Singapura':'Singapura',
    'Síria':'Damasco',
    'Somália':'Mogadíscio',
    'Sri Lanca':'Sri Jaiavardenapura-Cota',
    'Sudão':'Cartum',
    'Sudão do Sul':'Juba',
    'Suécia':'Estocolmo',
    'Suíça':'Berna',
    'Suriname':'Paramaribo',
    'Tailândia':'Banguecoque',
    'Taiuã':'Taipé',
    'Tajiquistão':'Duchambé',
    'Tanzânia':'Dodoma',
    'Timor-Leste':'Díli',
    'Togo':'Lomé',
    'Tonga':'Nucualofa',
    'Trindade e Tobago':'Porto de Espanha',
    'Tunísia':'Tunes',
    'Turcomenistão':'Asgabate',
    'Turquia':'Ancara',
    'Tuvalu':'Funafuti',
    'Ucrânia':'Quieve',
    'Uganda':'Campala',
    'Uruguai':'Montevideu',
    'Usbequistão':'Tasquente',
    'Vanuatu':'Porto Vila',
    'Vaticano':'Vaticano',
    'Venezuela':'Caracas',
    'Vietname':'Hanói',
    'Zâmbia':'Lusaca',
    'Zimbábue':'Harare'
    }