paises = {
    'Afeganistão':['Cabul',6],
    'África do Sul':['Pretória',5],
    'Albânia':['Tirana',4],
    'Alemanha':['Berlim',4],
    'Andorra':['Andorra-a-Velha',4],
    'Angola':['Luanda',5],
    'Antiga e Barbuda':['São João',2],
    'Arábia Saudita':['Riade',6],
    'Argélia':['Argel',5],
    'Argentina':['Buenos Aires',1],
    'Arménia':['Erevã',4],
    'Austrália':['Camberra',7],
    'Áustria':['Viena',4],
    'Azerbaijão':['Bacu',6],
    'Bahamas':['Nassau',2],
    'Bangladexe':['Daca',6],
    'Barbados':['Bridgetown',2],
    'Barém':['Manama',6],
    'Bélgica':['Bruxelas',4],
    'Belize':['Belmopã',2],
    'Benim':['Porto Novo',5],
    'Bielorrússia':['Minsque',4],
    'Bolívia':['Sucre',1],
    'Bósnia e Herzegovina':['Saraievo',4],
    'Botsuana':['Gaborone',5],
    'Brasil':['Brasília',1],
    'Brunei':['Bandar Seri Begauã',6],
    'Bulgária':['Sófia',4],
    'Burquina Faso':['Uagadugu',5],
    'Burúndi':['Bujumbura',5],
    'Butão':['Timbu',6],
    'Cabo Verde':['Praia',5],
    'Camarões':['Iaundé',5],
    'Camboja':['Pnom Pene',6],
    'Canadá':['Otava',3],
    'Catar':['Doha',6],
    'Cazaquistão':['Astana',6],
    'Chade':['Jamena',5],
    'Chile':['Santiago',1],
    'China':['Pequim',6],
    'Chipre':['Nicósia',4],
    'Colômbia':['Bogotá',1],
    'Comores':['Moroni',5],
    'Congo-Brazzaville':['Brazavile',5],
    'Coreia do Norte':['Pionguiangue',6],
    'Coreia do Sul':['Seul',6],
    'Cosovo':['Pristina',4],
    'Costa do Marfim':['Iamussucro',5],
    'Costa Rica':['São José',2],
    'Croácia':['Zagrebe',4],
    'Kuwait':['Cidade do Cuaite',6],
    'Cuba':['Havana',2],
    'Dinamarca':['Copenhaga',4],
    'Dominica':['Roseau',2],
    'Egito':['Cairo',6],
    'Emirados Árabes Unidos':['Abu Dabi',6],
    'Equador':['Quito',1],
    'Eritreia':['Asmara',5],
    'Eslováquia':['Bratislava',4],
    'Eslovénia':['Liubliana',4],
    'Espanha':['Madrid',4],
    'Essuatíni':['Lobamba',5],
    'Estado da Palestina':['Jerusalém Oriental',6],
    'Estados Unidos':['Washington D.C.',3],
    'Estónia':['Talim',4],
    'Etiópia':['Adis Abeba',5],
    'Fiji':['Suva',7],
    'Filipinas':['Manila',6],
    'Finlândia':['Helsínquia',4],
    'França':['Paris',4],
    'Gabão':['Libreville',5],
    'Gâmbia':['Banjul',5],
    'Gana':['Acra',5],
    'Geórgia':['Tebilíssi',4],
    'Granada':['São Jorge',2],
    'Grécia':['Atenas',4],
    'Guatemala':['Cidade da Guatemala',2],
    'Guiana':['Georgetown',1],
    'Guiné':['Conacri',5],
    'Guiné Equatorial':['Malabo',5],
    'Guiné-Bissau':['Bissau',5],
    'Haiti':['Porto Príncipe',2],
    'Honduras':['Tegucigalpa',2],
    'Hungria':['Budapeste',4],
    'Iémen':['Saná',6],
    'Ilhas Marechal':['Majuro',7],
    'Índia':['Nova Déli',6],
    'Indonésia':['Jacarta',6],
    'Irão':['Teerão',6],
    'Iraque':['Bagdade',6],
    'Irlanda':['Dublim',4],
    'Islândia':['Reiquiavique',4],
    'Israel':['Jerusalém',6],
    'Itália':['Roma',4],
    'Jamaica':['Kingston',2],
    'Japão':['Tóquio',6],
    'Jibuti':['Jibuti',5],
    'Jordânia':['Amã',6],
    'Laus':['Vienciana',6],
    'Lesoto':['Maseru',5],
    'Letónia':['Riga',4],
    'Líbano':['Beirute',6],
    'Libéria':['Monróvia',5],
    'Líbia':['Trípoli',5],
    'Listenstaine':['Vaduz',4],
    'Lituânia':['Vílnius',4],
    'Luxemburgo':['Luxemburgo',4],
    'Macedónia do Norte':['Escópia',4],
    'Madagáscar':['Antananarivo',5],
    'Malásia':['Cuala Lumpur',6],
    'Maláui':['Lilôngue',5],
    'Maldivas':['Malé',6],
    'Mali':['Bamaco',5],
    'Malta':['Valeta',4],
    'Marrocos':['Rebate',5],
    'Maurícia':['Porto Luís',5],
    'Mauritânia':['Nuaquechote',5],
    'México':['Cidade do México',3],
    'Mianmar':['Nepiedó',6],
    'Micronésia':['Paliquir',7],
    'Moçambique':['Maputo',5],
    'Moldávia':['Quixinau',4],
    'Mónaco':['Mónaco',4],
    'Mongólia':['Ulã Bator',6],
    'Montenegro':['Podgoritsa',4],
    'Namíbia':['Vinduque',5],
    'Nauru':['Iarém',7],
    'Nepal':['Catmandu',6],
    'Nicarágua':['Manágua',2],
    'Níger':['Niamei',5],
    'Nigéria':['Abuja',5],
    'Noruega':['Oslo',4],
    'Nova Zelândia':['Wellington',7],
    'Omã':['Mascate',6],
    'Países Baixos':['Amesterdão',4],
    'Palau':['Ngerulmud',7],
    'Panamá':['Cidade do Panamá',2],
    'Papua Nova Guiné':['Porto Moresby',7],
    'Paquistão':['Islamabade',6],
    'Paraguai':['Assunção',1],
    'Peru':['Lima',1],
    'Polónia':['Varsóvia',4],
    'Portugal':['Lisboa',4],
    'Quénia':['Nairóbi',5],
    'Quirguistão':['Bisqueque',6],
    'Quiribáti':['Taraua do Sul',7],
    'Reino Unido':['Londres',4],
    'República Centro-Africana':['Bangui',5],
    'República Checa':['Praga',4],
    'República Democrática do Congo':['Quinxassa',5],
    'República Dominicana':['São Domingos',2],
    'Roménia':['Bucareste',4],
    'Ruanda':['Quigali',5],
    'Rússia':['Moscovo',4],
    'Salomão':['Honiara',7],
    'El Salvador':['São Salvador',2],
    'Samoa':['Apia',7],
    'Santa Lúcia':['Castries',2],
    'São Cristóvão e Neves':['Basseterre',2],
    'São Marinho':['São Marinho',2],
    'São Tomé e Príncipe':['São Tomé',2],
    'São Vicente e Granadinas':['Kingstown',2],
    'Seicheles':['Vitória',5],
    'Senegal':['Dacar',5],
    'Serra Leoa':['Freetown',5],
    'Sérvia':['Belgrado',4],
    'Singapura':['Singapura',6],
    'Síria':['Damasco',6],
    'Somália':['Mogadíscio',5],
    'Sri Lanca':['Colombo',6],
    'Sudão':['Cartum',5],
    'Sudão do Sul':['Juba',5],
    'Suécia':['Estocolmo',4],
    'Suíça':['Berna',4],
    'Suriname':['Paramaribo',1],
    'Tailândia':['Banguecoque',6],
    'Taiwan':['Taipé',6],
    'Tajiquistão':['Duchambé',6],
    'Tanzânia':['Dodoma',5],
    'Timor-Leste':['Díli',7],
    'Togo':['Lomé',5],
    'Tonga':['Nucualofa',7],
    'Trindade e Tobago':['Porto de Espanha',2],
    'Tunísia':['Tunes',5],
    'Turcomenistão':['Asgabate',6],
    'Turquia':['Ancara',4],
    'Tuvalu':['Funafuti',7],
    'Ucrânia':['Quieve',4],
    'Uganda':['Campala',5],
    'Uruguai':['Montevideu',1],
    'Usbequistão':['Tasquente',6],
    'Vanuatu':['Porto Vila',7],
    'Vaticano':['Vaticano',4],
    'Venezuela':['Caracas',1],
    'Vietname':['Hanói',6],
    'Zâmbia':['Lusaca',5],
    'Zimbábue':['Harare',5]    
}

continente = {
    1:'América do Sul',
    2:'América Central',
    3:'América do Norte',
    4:'Europa',
    5:'África',
    6:'Ásia',
    7:'Oceania'
}
    
